name: phishfence
channels:
  - conda-forge
dependencies:
  - python >=3.13,<3.14
  - pandas
  - ipykernel
  - numpy
  - scikit-learn
  - pytorch
  - transformers
  - seaborn
  - matplotlib
  - nltk
  - tldextract
  - tabulate
  - shap
<<<<<<< HEAD
  - sentence-transformers
=======
  - python-dotenv
>>>>>>> 7560befc31d083a3f93f9c7066f4167e840d4ce3
