name: phishfence
channels:
  - conda-forge
dependencies:
  - python >=3.13,<3.14
  - pandas
  - ipykernel
  - numpy
  - scikit-learn
  - pytorch
  - transformers
  - seaborn
  - matplotlib
  - nltk
  - tldextract
  - tabulate
  - shap
  - sentence-transformers
  - python-dotenv
  - openai
  - flask
  - joblib
  - markupsafe
