name: phishfence-web
channels:
  - conda-forge
dependencies:
  - python >=3.13,<3.14
  - pip
  - pip:
      - flask
      - numpy
      - shap
      - transformers
      - torch
      - markupsafe
      - google-genai
